require 'nokogiri'

require 'batch_processor/version'
require 'batch_processor/destinations'
require 'batch_processor/destination'
require 'batch_processor/node_parent'
require 'batch_processor/node'
require 'batch_processor/taxonomies'
require 'batch_processor/destination_html'
require 'batch_processor/batcher'
require 'batch_processor/cli'
